### ISSUE TITLE
KeyError in @api.route(f'{USERS_EP}')

### ISSUE THREAD

**Issue by ebootehsaz** [SWEES-news/backend#1]
/backend/server/endpoints.py", line 174, in post
    name = request.json[usrs.NAME]
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Username'

When making a request to add game from frontend.

**Comment by elwhittle** [comment]
@ebootehsaz the request type should be delete now, maybe that's the cause? Is your backend up to date?
